### ISSUE TITLE
file upload node?

### ISSUE THREAD

**Issue by jixing475** [rstudio/shinyuieditor#104]
how to handle file upload?

**Comment by nstrayer** [comment]
Right now as we don't have the file upload ui element implemented you would manually write the code for it in your UI. Then you can move it around in your ui like you would otherwise just not adjust the settings.

![localhost_25761_](https://user-images.githubusercontent.com/6764693/195124384-2b933b23-bf1f-4790-9d28-9766c8a4770c.png)


```R
# Ui code of app
ui <- grid_page(
  layout = c(
    "header  header  ",
    "sidebar distPlot"
  ),
  row_sizes = c(
    "100px",
    "1fr"
  ),
  col_sizes = c(
    "310px",
    "1fr"
  ),
  gap_size = "1rem",
  grid_card(
    area = "sidebar",
    item_alignment = "top",
    title = "Settings",
    item_gap = "12px",
    sliderInput(
      inputId = "bins",
      label = "Number of Bins",
      min = 12L,
      max = 100L,
      value = 30L,
      width = "100%"
    ),
    shiny::fileInput(
      "myFile",
      "Upload a file"
    )
  ),
  grid_card_text(
    area = "header",
    content = "Single File App",
    alignment = "start",
    is_title = FALSE
  ),
  grid_card_plot(area = "distPlot")
)
```

Obviously not the prettiest solution but your issue is helpful to let us know what ui elements to prioritize adding going forward! Thanks so much! 

Feel free to reopen if anything isn't clear.
