### ISSUE TITLE
concern with design philosophy

### ISSUE THREAD

**Issue by apsteinmetz** [rstudio/shinyuieditor#193]
Hi, Nick.  Excuse this for being a buzzkill comment. shinyuieditor uses {gridlayout} as its basic layout builder. This is not the "native" shiny page layout code. So that's a bit confusing already.  Now it seems that Posit is promoting {bslib} and its page layout vernacular as the more "modern" way.  Does that leave this project as a dead-end?

**Comment by nstrayer** [comment]
This is a good (and sore) point! 

Gridlayout was conceived primarily as a method to layout dashboard-style apps. Bslib is more of a styling/component-level framework. That being said we do have a confusing narrative as to how to build dashboards at the moment, with lots of our examples using bslib entirely. 

Because gridlayout is so lightweight and for components etc we're using bslib cards etc I think it's fine but I agree that Shiny as a whole should have a clear narrative. Once that's completed, the UI editor can/will be updated to fit that. 

It is worth noting that you can use the bslib navbar page as the root of your app.

**Comment by nstrayer** [comment]
#194 fills a similar role to this. I'm going to close this with the idea of consolidating the discussion there. Please feel free to reopen if you think the two issues get at different things. This is definitely going to be a priority moving forward.
