### ISSUE TITLE
Error trying to access Tour in live demo

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shinyuieditor#227]
https://rstudio.github.io/shinyuieditor/live-demo/

Select a template, then click the Tour App button.

<img width="617" alt="image" src="https://github.com/rstudio/shinyuieditor/assets/129551/052c8c77-a97f-4778-b771-2d047b6cf0fd">

**Comment by nstrayer** [comment]
Much like #226 this points to needing e2e tests of the tour mode. This one is due to the tour library using `global` which, when the editor is embedded as a component into an islands architecture app, doesn't exist like it expects. Should be a fairly easy fix in the build config for the website.

**Comment by nstrayer** [comment]
Oof, turns out I had already dealt with this. The tour mode uses `react-floater` which hasn't been updated in a while and relies on webpack conventions of putting in a `global` variable that would typically just be `window`. The bandaid is to just assign `global` to `window` somewhere before the tour code gets run. I already did this in the main versions of the app in the html template but neglected to do it in the website version. Is fixed in #239.
